export type ProductVariant = {
  name: string;
  value: string;
  price?: number;
  stock: number;
};

export type Product = {
  id: string;
  title: string;
  slug: string;
  category: string;
  kind: "course" | "book" | "tool";
  price: number;
  oldPrice: number;
  images: string[];
  desc: string;
  level: string;
  duration: string;
  students: string;
  rating: number;
  reviewCount: string;
  includes: string[];
  downloadUrl?: string;
  variants?: ProductVariant[];
  featured?: boolean;
  badge?: "Hot" | "Bestseller" | "New";
  tags?: string[];
  createdAt: string;
};

export const CATEGORIES = [
  { key: "Hacking", label: "Hacking", icon: "shield", image: "/images/ethical-hacking-pentest.jpeg" },
  { key: "Programming", label: "Programming", icon: "code", image: "/images/python-complete.jpeg" },
  { key: "Trading", label: "Trading", icon: "chart", image: "/images/mindfluential-trading.jpeg" },
  { key: "Books", label: "Digital Books", icon: "book", image: "/images/hacking-bible.jpeg" },
  { key: "Tools", label: "Software & Tools", icon: "wrench", image: "/images/slide-hacker.jpg" },
  { key: "Design", label: "Design", icon: "palette", image: "/images/uiux-design.jpeg" },
  { key: "Marketing", label: "Marketing", icon: "megaphone", image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop" },
] as const;

const img = "?w=800&auto=format&fit=crop";

export const products: Product[] = [
  {
    id: "h1",
    title: "Complete Ethical Hacking & Penetration Testing",
    slug: "complete-ethical-hacking-penetration-testing",
    category: "Hacking",
    kind: "course",
    price: 199,
    oldPrice: 499,
    images: ["/images/ethical-hacking-pentest.jpeg"],
    desc: "Master ethical hacking from scratch. Learn penetration testing, network security, vulnerability assessment, and become a certified ethical hacker.",
    level: "Advanced",
    duration: "48 hours",
    students: "12,500",
    rating: 4.9,
    reviewCount: "3,200",
    includes: ["48 hours of HD video content", "35+ hands-on lab exercises", "Certificate of completion", "Lifetime access", "15 real-world hacking projects", "Downloadable resources"],
    variants: [{ name: "Level", value: "Advanced", stock: 999 }, { name: "Access", value: "Lifetime", stock: 999 }],
    featured: true,
    badge: "Hot",
    tags: ["bestseller", "certification"],
    createdAt: "2024-01-05",
  },
  {
    id: "h2",
    title: "Web Application Hacking & Security",
    slug: "web-application-hacking-security",
    category: "Hacking",
    kind: "course",
    price: 249,
    oldPrice: 599,
    images: ["/images/web-app-hacking.jpeg"],
    desc: "Learn to hack web applications ethically. Master OWASP Top 10, SQL injection, XSS, CSRF, and secure coding practices.",
    level: "Intermediate",
    duration: "35 hours",
    students: "8,200",
    rating: 4.8,
    reviewCount: "2,100",
    includes: ["35 hours of HD video", "25+ web hacking labs", "Bug bounty methodology", "Certificate of completion", "Lifetime access"],
    featured: true,
    badge: "Bestseller",
    createdAt: "2024-01-10",
  },
  {
    id: "h3",
    title: "Advanced Ethical Hacking: Keylogger Mastery",
    slug: "advanced-ethical-hacking-keylogger-mastery",
    category: "Hacking",
    kind: "course",
    price: 199,
    oldPrice: 499,
    images: ["/images/keylogger-mastery.jpeg"],
    desc: "Master advanced keylogger development and deployment techniques for penetration testing.",
    level: "Advanced",
    duration: "18 hours",
    students: "6,800",
    rating: 4.8,
    reviewCount: "1,200",
    downloadUrl: "https://www.mediafire.com/file/nqp829z49i2rco9/Advanced_Ethical_Hacking_Keylogger_Tutorial.rar/file",
    includes: ["18 hours of HD video", "Keylogger development labs", "Windows & Linux keyloggers", "Evasion techniques", "Certificate of completion"],
    createdAt: "2024-02-02",
  },
  {
    id: "h4",
    title: "Reverse Engineering: The Hacks Behind Cracking",
    slug: "reverse-engineering-hacks-behind-cracking",
    category: "Hacking",
    kind: "course",
    price: 249,
    oldPrice: 599,
    images: ["/images/reverse-engineering.jpeg"],
    desc: "Deep dive into reverse engineering and software cracking. Learn disassembly, debugging, and binary analysis.",
    level: "Advanced",
    duration: "22 hours",
    students: "5,400",
    rating: 4.9,
    reviewCount: "980",
    downloadUrl: "https://www.mediafire.com/file/es1e9lx0c9vk80k/Dedsec_Reverse_Engineering_Course_%25E2%2580%2593_The_Hacks_Behind_Cracking_2.rar/file",
    includes: ["22 hours of HD video", "x86 & x64 disassembly", "OllyDbg & IDA Pro labs", "Crackme challenges", "Certificate of completion"],
    createdAt: "2024-02-14",
  },
  {
    id: "h5",
    title: "Complete Hacking Course: Beginner to Pro",
    slug: "complete-hacking-course-beginner-to-pro",
    category: "Hacking",
    kind: "course",
    price: 199,
    oldPrice: 499,
    images: ["/images/hacking-beginner-pro.jpeg"],
    desc: "The most comprehensive hacking course for beginners. Learn network scanning, vulnerability assessment, and more.",
    level: "Beginner",
    duration: "40 hours",
    students: "15,200",
    rating: 4.7,
    reviewCount: "2,800",
    downloadUrl: "https://www.mediafire.com/file/wcp053dntrt3dql/hacking_course_vansh.rar/file",
    includes: ["40 hours of HD video", "50+ hands-on labs", "Kali Linux setup guide", "Network hacking techniques", "Certificate of completion"],
    badge: "Bestseller",
    createdAt: "2024-01-15",
  },
  {
    id: "h6",
    title: "Masters in Ethical Hacking: Course 2",
    slug: "masters-in-ethical-hacking-course-2",
    category: "Hacking",
    kind: "course",
    price: 249,
    oldPrice: 599,
    images: ["/images/ethical-hacking-masters-2.jpeg"],
    desc: "Advanced ethical hacking course covering penetration testing, exploit development, and privilege escalation.",
    level: "Advanced",
    duration: "36 hours",
    students: "9,100",
    rating: 4.8,
    reviewCount: "1,650",
    downloadUrl: "https://www.mediafire.com/file/qnnw2a5syl8meua/Masters-In-Ethical-Hacking-Course-2-Gib-.rar/file",
    includes: ["36 hours of HD video", "Advanced exploitation labs", "Privilege escalation techniques", "Active Directory attacks", "Certificate of completion"],
    createdAt: "2024-03-01",
  },
  {
    id: "h7",
    title: "Dedsec Facebook & Instagram Hacking",
    slug: "dedsec-facebook-instagram-hacking",
    category: "Hacking",
    kind: "course",
    price: 199,
    oldPrice: 499,
    images: [`https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0${img}`],
    desc: "Learn Facebook and Instagram security testing and social engineering attacks.",
    level: "Intermediate",
    duration: "20 hours",
    students: "7,500",
    rating: 4.7,
    reviewCount: "1,100",
    downloadUrl: "https://www.mediafire.com/file/y8vqdghh5scv6pp/Dedsec_Facebook_%2526_Instagram_Hacking_Course_%25281%2529.rar/file",
    includes: ["20 hours of HD video", "Social media reconnaissance", "Account security testing", "Phishing techniques"],
    createdAt: "2024-03-10",
  },
  {
    id: "h8",
    title: "Dedsec Antivirus Evasion Course",
    slug: "dedsec-antivirus-evasion-course",
    category: "Hacking",
    kind: "course",
    price: 249,
    oldPrice: 599,
    images: [`https://images.unsplash.com/photo-1550751827-4bd374c3f58b${img}`],
    desc: "Master antivirus evasion techniques. Learn to bypass AV detection.",
    level: "Advanced",
    duration: "18 hours",
    students: "5,200",
    rating: 4.8,
    reviewCount: "900",
    downloadUrl: "https://www.mediafire.com/file/mc4oytl376jb39l/Dedsec__Antivirus_Evasion_Course_By_.rar/file",
    includes: ["18 hours of HD video", "AV bypass methods", "Payload obfuscation", "Runtime detection evasion"],
    badge: "Hot",
    createdAt: "2024-03-20",
  },
  {
    id: "h34",
    title: "Advance Practical Phishing Course",
    slug: "advance-practical-phishing-course",
    category: "Hacking",
    kind: "course",
    price: 299,
    oldPrice: 699,
    images: [`https://images.unsplash.com/photo-1504639725590-34d0984388bd${img}`],
    desc: "Master advanced phishing techniques. Learn email phishing, spear phishing, and credential harvesting.",
    level: "Advanced",
    duration: "20 hours",
    students: "8,500",
    rating: 4.8,
    reviewCount: "1,500",
    downloadUrl: "https://www.mediafire.com/file/3zu4iloqbrl6tvf/Advance-Practical-Phishing-course.zip/file",
    includes: ["20 hours of HD video", "Phishing page creation", "Email phishing templates", "Credential harvesting"],
    createdAt: "2024-04-05",
  },
  {
    id: "p1",
    title: "Python Complete Course: Beginner to Advanced",
    slug: "python-complete-course-beginner-to-advanced",
    category: "Programming",
    kind: "course",
    price: 199,
    oldPrice: 499,
    images: ["/images/python-complete.jpeg"],
    desc: "Master Python programming from zero to hero. Learn data structures, OOP, web scraping, and build 10+ real projects.",
    level: "All Levels",
    duration: "42 hours",
    students: "45,000",
    rating: 4.9,
    reviewCount: "5,100",
    includes: ["42 hours of HD video", "200+ coding exercises", "10+ real projects", "Certificate of completion", "Lifetime access"],
    featured: true,
    badge: "Bestseller",
    createdAt: "2024-01-08",
  },
  {
    id: "p2",
    title: "Complete JavaScript Mastery",
    slug: "complete-javascript-mastery",
    category: "Programming",
    kind: "course",
    price: 249,
    oldPrice: 599,
    images: ["/images/javascript-mastery.jpeg"],
    desc: "Become a JavaScript expert. Learn ES6+, DOM manipulation, async programming, and build 15+ projects.",
    level: "Advanced",
    duration: "45 hours",
    students: "32,000",
    rating: 4.9,
    reviewCount: "2,500",
    includes: ["45 hours of HD video", "300+ coding challenges", "15+ projects", "Certificate of completion", "Lifetime access"],
    featured: true,
    createdAt: "2024-02-01",
  },
  {
    id: "p3",
    title: "React & Next.js Developer Guide",
    slug: "react-nextjs-developer-guide",
    category: "Programming",
    kind: "course",
    price: 199,
    oldPrice: 499,
    images: [`https://images.unsplash.com/photo-1633356122544-f134324a6cee${img}`],
    desc: "Master React and Next.js. Learn hooks, state management, routing, SSR, and build production-ready apps.",
    level: "Intermediate",
    duration: "50 hours",
    students: "28,000",
    rating: 4.8,
    reviewCount: "2,200",
    includes: ["50 hours of HD video", "React 18 & Next.js 14", "8 portfolio projects", "Certificate of completion"],
    createdAt: "2024-02-20",
  },
  {
    id: "p4",
    title: "Complete Java Coding Course",
    slug: "complete-java-coding-course",
    category: "Programming",
    kind: "course",
    price: 249,
    oldPrice: 599,
    images: [`https://images.unsplash.com/photo-1517694712202-14dd9538aa97${img}`],
    desc: "Master Java programming from basics to advanced. Learn OOP, collections, multithreading and build real apps.",
    level: "Beginner",
    duration: "40 hours",
    students: "21,000",
    rating: 4.8,
    reviewCount: "1,800",
    includes: ["40 hours of HD video", "150+ coding exercises", "Java projects", "Certificate of completion"],
    badge: "Bestseller",
    createdAt: "2024-03-15",
  },
  {
    id: "t1",
    title: "Stock Market Mastery: Zero to Pro",
    slug: "stock-market-mastery-zero-to-pro",
    category: "Trading",
    kind: "course",
    price: 0,
    oldPrice: 0,
    images: [`https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3${img}`],
    desc: "Complete stock market trading course. Learn technical analysis, chart patterns, and risk management.",
    level: "All Levels",
    duration: "38 hours",
    students: "18,500",
    rating: 4.7,
    reviewCount: "2,600",
    includes: ["38 hours of HD video", "Live trading sessions", "Chart analysis techniques", "Risk management system"],
    featured: true,
    badge: "Hot",
    createdAt: "2024-01-20",
  },
  {
    id: "t2",
    title: "Crypto Trading Pro: Bitcoin & Altcoins",
    slug: "crypto-trading-pro-bitcoin-altcoins",
    category: "Trading",
    kind: "course",
    price: 249,
    oldPrice: 599,
    images: [`https://images.unsplash.com/photo-1621761191319-c6fb62004040${img}`],
    desc: "Master cryptocurrency trading. Learn DeFi, NFTs, technical analysis for crypto.",
    level: "Intermediate",
    duration: "30 hours",
    students: "22,000",
    rating: 4.8,
    reviewCount: "1,900",
    includes: ["30 hours of HD video", "DeFi & Web3 covered", "Portfolio management", "Certificate of completion"],
    createdAt: "2024-02-11",
  },
  {
    id: "t3",
    title: "Forex Trading: Complete Beginners Guide",
    slug: "forex-trading-complete-beginners-guide",
    category: "Trading",
    kind: "course",
    price: 199,
    oldPrice: 499,
    images: [`https://images.unsplash.com/photo-1535320903710-d993d3d77d29${img}`],
    desc: "Learn forex trading from scratch. Master currency pairs, leverage, and technical analysis.",
    level: "Beginner",
    duration: "25 hours",
    students: "15,000",
    rating: 4.6,
    reviewCount: "1,300",
    includes: ["25 hours of HD video", "Demo account practice", "Live market analysis", "Certificate of completion"],
    createdAt: "2024-03-05",
  },
  {
    id: "t4",
    title: "Complete Stock Market Course",
    slug: "complete-stock-market-course",
    category: "Trading",
    kind: "course",
    price: 249,
    oldPrice: 599,
    images: [`https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f${img}`],
    desc: "Master the stock market from fundamentals to advanced trading strategies.",
    level: "All Levels",
    duration: "32 hours",
    students: "22,500",
    rating: 4.7,
    reviewCount: "1,700",
    downloadUrl: "https://www.mediafire.com/file/43igah1dqfqqc26/Complete_Stock_Market_course_%255BHACKSNATION.COM%255D.zip/file",
    includes: ["32 hours of HD video", "Live market analysis", "Technical & fundamental analysis", "Portfolio management"],
    createdAt: "2024-04-01",
  },
  {
    id: "t5",
    title: "Mindfluential Trading: Psychology & Strategy",
    slug: "mindfluential-trading-psychology-strategy",
    category: "Books",
    kind: "book",
    price: 1,
    oldPrice: 99,
    images: ["/images/mindfluential-trading.jpeg"],
    desc: "Master the mental game of trading. Comprehensive guide to trading psychology and strategies.",
    level: "All Levels",
    duration: "PDF Book",
    students: "4,200",
    rating: 4.8,
    reviewCount: "700",
    downloadUrl: "https://www.mediafire.com/file/4fo3qqyonf9fg9o/3._Mindfluential_Trading.pdf/file",
    includes: ["PDF format (320+ pages)", "Real trader case studies", "Emotional control techniques", "Trading plan templates"],
    badge: "New",
    createdAt: "2024-04-10",
  },
  {
    id: "b1",
    title: "The Hacking Bible: Complete Guide",
    slug: "the-hacking-bible-complete-guide",
    category: "Books",
    kind: "book",
    price: 1,
    oldPrice: 99,
    images: ["/images/hacking-bible.jpeg"],
    desc: "The ultimate hacking reference book. Covers everything from basic concepts to advanced techniques.",
    level: "Advanced",
    duration: "PDF Book",
    students: "5,200",
    rating: 4.8,
    reviewCount: "1,100",
    includes: ["PDF format (450+ pages)", "Practical examples", "Step-by-step guides", "Bonus cheat sheets"],
    badge: "Bestseller",
    createdAt: "2024-01-25",
  },
  {
    id: "b2",
    title: "Trading Psychology: Master Your Mind",
    slug: "trading-psychology-master-your-mind",
    category: "Books",
    kind: "book",
    price: 1,
    oldPrice: 79,
    images: ["/images/trading-psychology.jpeg"],
    desc: "Master the psychology of trading. Learn to control emotions and build discipline.",
    level: "All Levels",
    duration: "PDF Book",
    students: "3,800",
    rating: 4.7,
    reviewCount: "650",
    includes: ["PDF format (280+ pages)", "Case studies", "Self-assessment tools", "Bonus worksheets"],
    createdAt: "2024-02-05",
  },
  {
    id: "b3",
    title: "Python Crash Course: Complete Guide",
    slug: "python-crash-course-complete-guide",
    category: "Books",
    kind: "book",
    price: 1,
    oldPrice: 99,
    images: ["/images/python-crash-course.jpeg"],
    desc: "Learn Python programming through this comprehensive guide. Perfect for beginners.",
    level: "Beginner",
    duration: "PDF Book",
    students: "12,000",
    rating: 4.9,
    reviewCount: "2,100",
    includes: ["PDF format (380+ pages)", "Code examples", "Practice exercises", "Project ideas"],
    badge: "Bestseller",
    createdAt: "2024-02-08",
  },
  {
    id: "b10",
    title: "WooCommerce WordPress Tutorial (Hindi)",
    slug: "woocommerce-wordpress-tutorial-hindi",
    category: "Books",
    kind: "book",
    price: 1,
    oldPrice: 79,
    images: [`https://images.unsplash.com/photo-1532012197267-da84d127e765${img}`],
    desc: "Complete WooCommerce + WordPress tutorial in Hindi. Build your own online store step by step.",
    level: "Beginner",
    duration: "PDF Book",
    students: "6,000",
    rating: 4.6,
    reviewCount: "1,900",
    includes: ["PDF format (300+ pages)", "WordPress setup guide", "WooCommerce configuration", "Live examples"],
    badge: "New",
    createdAt: "2024-05-01",
  },
  {
    id: "d1",
    title: "UI/UX Design Complete Course",
    slug: "ui-ux-design-complete-course",
    category: "Design",
    kind: "course",
    price: 199,
    oldPrice: 499,
    images: ["/images/uiux-design.jpeg"],
    desc: "Master UI/UX design from wireframes to high-fidelity prototypes. Learn Figma and Adobe XD.",
    level: "Beginner",
    duration: "38 hours",
    students: "20,000",
    rating: 4.8,
    reviewCount: "1,800",
    includes: ["38 hours of HD video", "Figma & Adobe XD", "10 design projects", "Certificate of completion"],
    featured: true,
    badge: "Hot",
    createdAt: "2024-02-15",
  },
  {
    id: "d2",
    title: "UI/UX Design Fundamentals",
    slug: "ui-ux-design-fundamentals",
    category: "Design",
    kind: "course",
    price: 249,
    oldPrice: 599,
    images: [`https://images.unsplash.com/photo-1561070791-2526d30994b5${img}`],
    desc: "Learn UI/UX fundamentals: color theory, typography, layout grids and design systems.",
    level: "Beginner",
    duration: "30 hours",
    students: "15,500",
    rating: 4.7,
    reviewCount: "2,400",
    includes: ["30 hours of HD video", "Design system basics", "Figma exercises", "Portfolio project"],
    badge: "New",
    createdAt: "2024-05-10",
  },
  {
    id: "m1",
    title: "Digital Marketing Masterclass",
    slug: "digital-marketing-masterclass",
    category: "Marketing",
    kind: "course",
    price: 199,
    oldPrice: 499,
    images: [`https://images.unsplash.com/photo-1460925895917-afdab827c52f${img}`],
    desc: "Complete digital marketing course. Learn SEO, social media marketing, Google Ads, and more.",
    level: "All Levels",
    duration: "35 hours",
    students: "25,000",
    rating: 4.7,
    reviewCount: "3,100",
    includes: ["35 hours of HD video", "Google Ads certification prep", "SEO tools training", "Certificate of completion"],
    createdAt: "2024-03-12",
  },
  {
    id: "m3",
    title: "Digital Marketing Video Course",
    slug: "digital-marketing-video-course",
    category: "Marketing",
    kind: "course",
    price: 199,
    oldPrice: 499,
    images: [`https://images.unsplash.com/photo-1533750349088-cd871a92f312${img}`],
    desc: "Video-based digital marketing course covering Facebook ads, Instagram growth and YouTube growth.",
    level: "Beginner",
    duration: "30 hours",
    students: "18,000",
    rating: 4.7,
    reviewCount: "1,600",
    includes: ["30 hours of HD video", "Facebook ads training", "Instagram growth hacks", "YouTube SEO"],
    badge: "Bestseller",
    createdAt: "2024-04-20",
  },
  {
    id: "h24",
    title: "888RAT Remote Access Tool",
    slug: "888rat-remote-access-tool",
    category: "Tools",
    kind: "tool",
    price: 399,
    oldPrice: 999,
    images: [`https://images.unsplash.com/photo-1563206767-5b18f218e8de${img}`],
    desc: "888RAT is a powerful remote access tool for system administration and security testing.",
    level: "Advanced",
    duration: "Tool",
    students: "3,200",
    rating: 4.5,
    reviewCount: "400",
    downloadUrl: "https://www.mediafire.com/file/adddhsuj00bl4yx/888RAT_1.1.1_RAT_Cracked.7z/file",
    includes: ["Cracked version included", "Remote desktop access", "File management", "Keylogger module"],
    createdAt: "2024-01-30",
  },
  {
    id: "h25",
    title: "AhMyth Win32 Hacking RAT",
    slug: "ahmyth-win32-hacking-rat",
    category: "Tools",
    kind: "tool",
    price: 0,
    oldPrice: 0,
    images: [`https://images.unsplash.com/photo-1555066931-4365d14bab8c${img}`],
    desc: "AhMyth is an open-source RAT for Win32 systems. Learn remote administration.",
    level: "Intermediate",
    duration: "Tool",
    students: "4,500",
    rating: 4.6,
    reviewCount: "500",
    downloadUrl: "https://www.mediafire.com/file/m59ylitvtw85i7y/AhMyth_Win32_Hacking_Rat.zip/file",
    includes: ["Win32 version", "Remote shell", "Screen capture", "File explorer"],
    createdAt: "2024-02-18",
  },
  {
    id: "h26",
    title: "AhMyth Win64 Hacking RAT",
    slug: "ahmyth-win64-hacking-rat",
    category: "Tools",
    kind: "tool",
    price: 0,
    oldPrice: 0,
    images: [`https://images.unsplash.com/photo-1555066931-4365d14bab8c${img}`],
    desc: "AhMyth Win64 version with enhanced features for 64-bit systems.",
    level: "Intermediate",
    duration: "Tool",
    students: "4,100",
    rating: 4.6,
    reviewCount: "450",
    downloadUrl: "https://www.mediafire.com/file/dog2ifd1eo66n4b/AhMyth_Win64_Hacking_Rat2.zip/file",
    includes: ["Win64 version", "Enhanced performance", "64-bit support", "Remote administration"],
    createdAt: "2024-02-19",
  },
  {
    id: "h27",
    title: "AndroRAT - Android RAT",
    slug: "androrat-android-rat",
    category: "Tools",
    kind: "tool",
    price: 0,
    oldPrice: 0,
    images: [`https://images.unsplash.com/photo-1612178991541-b48cc8e92a4e${img}`],
    desc: "AndroRAT is an Android-based RAT for remote device management.",
    level: "Intermediate",
    duration: "Tool",
    students: "5,800",
    rating: 4.7,
    reviewCount: "600",
    downloadUrl: "https://www.mediafire.com/file/oeludagegihhcye/AndroRAT_-_AndroBinder.zip/file",
    includes: ["Android RAT tool", "Binder integration", "SMS access", "GPS tracking"],
    badge: "Hot",
    createdAt: "2024-02-22",
  },
  {
    id: "h28",
    title: "Cerberus RAT 1.0 Beta",
    slug: "cerberus-rat-1-0-beta",
    category: "Tools",
    kind: "tool",
    price: 0,
    oldPrice: 0,
    images: [`https://images.unsplash.com/photo-1563206767-5b18f218e8de${img}`],
    desc: "Cerberus RAT is an advanced remote access tool with modern features.",
    level: "Advanced",
    duration: "Tool",
    students: "2,900",
    rating: 4.5,
    reviewCount: "350",
    downloadUrl: "https://www.mediafire.com/file/98j330zzb9pebvd/Cerberus_RAT_1.0_Beta.rar/file",
    includes: ["Beta version included", "Remote desktop", "Credential harvesting", "Persistence module"],
    createdAt: "2024-03-08",
  },
  {
    id: "h29",
    title: "DroidJack Complete Setup RAT",
    slug: "droidjack-complete-setup-rat",
    category: "Tools",
    kind: "tool",
    price: 0,
    oldPrice: 0,
    images: [`https://images.unsplash.com/photo-1612178991541-b48cc8e92a4e${img}`],
    desc: "DroidJack is a powerful Android RAT with complete setup guide.",
    level: "Advanced",
    duration: "Tool",
    students: "6,200",
    rating: 4.7,
    reviewCount: "700",
    downloadUrl: "https://www.mediafire.com/file/tyvxvad18uyy6ig/Droid_Jack_Complete_Setup_Hacking_Rat.zip/file",
    includes: ["Complete setup included", "Android remote control", "SMS & call logs", "Camera access"],
    createdAt: "2024-03-18",
  },
  {
    id: "h30",
    title: "NanoCore RAT 1.2.2.0",
    slug: "nanocore-rat",
    category: "Tools",
    kind: "tool",
    price: 0,
    oldPrice: 0,
    images: [`https://images.unsplash.com/photo-1563206767-5b18f218e8de${img}`],
    desc: "NanoCore is a premium RAT with advanced features. Cracked version included.",
    level: "Advanced",
    duration: "Tool",
    students: "7,500",
    rating: 4.8,
    reviewCount: "800",
    downloadUrl: "https://www.mediafire.com/file/10erodudviikc16/NanoCore_RAT_1.2.2.0_Cracked.7z/file",
    includes: ["Fully cracked version", "Plugin system", "Remote desktop", "File manager"],
    badge: "Bestseller",
    createdAt: "2024-03-25",
  },
];

export function getCategoryProducts(category: string): Product[] {
  return products.filter((p) => p.category.toLowerCase() === category.toLowerCase());
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter((p) => p.id !== product.id && (p.category === product.category || p.tags?.some((t) => product.tags?.includes(t))))
    .slice(0, limit);
}

export function getFeaturedProducts(limit = 8): Product[] {
  return products.filter((p) => p.price > 0).slice(0, limit);
}

export function searchProducts(query: string): Product[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return products
    .filter(
      (p) =>
        p.title.toLowerCase().includes(q) ||
        p.category.toLowerCase().includes(q) ||
        p.desc.toLowerCase().includes(q) ||
        (p.tags || []).some((t) => t.includes(q))
    )
    .slice(0, 6);
}

export function formatINR(n: number): string {
  if (n <= 0) return "FREE";
  return "₹" + n.toLocaleString("en-IN");
}